/**
 * persistent-memory — bootstrap seed (Phase 2)
 *
 * Idempotent. Creates, on a fresh database:
 *   1. The first SUPERUSER — an INDEPENDENT, TEAM-LESS global super-admin
 *      (admin_level=superuser, team_id=NULL) + an opaque token, emitted to
 *      stdout EXACTLY ONCE. install.sh shows it with a "copy now" banner; it is
 *      NEVER written to the DB or logs (only tokenId + argon2id(tokenHash)
 *      persist). The admin then creates teams + team-bound users from the
 *      dashboard. (See docs/internal/users_roles.md.)
 *   2. Two demo teams — "Automation QA" and "Manual QA" — for convenience.
 *   3. One sample MOUNT (directional grant): Manual QA mounts Automation QA, so
 *      Manual QA's MCP reads Automation QA's memories (read-only; MCP-only).
 *
 * IDEMPOTENCY IS A SECURITY CONTROL: the run is gated on
 * `count(admin_level='superuser') >= 1`. Without the gate, every install.sh run
 * would mint a fresh live token (credential leak). Re-running after bootstrap is
 * a no-op for the superuser; teams/mount are upserted.
 *
 * CONNECTION: run as the OWNER (DATABASE_MIGRATE_URL → pmuser) so it can write
 * the control tables. The runtime role pm_app is NOT used here.
 *
 * Token wire format: `${tokenId}.${secret}`. The API splits on '.', looks up by
 * tokenId (indexed, @unique), then argon2id-verifies secret against tokenHash.
 */

import { randomBytes } from 'node:crypto'
import { chmod, writeFile } from 'node:fs/promises'
import { PrismaPg } from '@prisma/adapter-pg'
import argon2 from 'argon2'
// Generated by `prisma generate` (Prisma 7 `prisma-client` generator → ../../../generated/prisma).
import { PrismaClient } from '../../../generated/prisma/client.ts'

// Owner connection: prefer the dedicated migrate URL, fall back to DATABASE_URL
// for local one-shot runs where the split role does not exist yet.
const connectionString =
  process.env.DATABASE_MIGRATE_URL ?? process.env.DATABASE_URL
if (!connectionString) {
  throw new Error('DATABASE_MIGRATE_URL (or DATABASE_URL) must be set to seed.')
}

const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

// ── Argon2id params (kept in lockstep with the API verifier in P3). ──────────
const argonOptions: argon2.Options = {
  type: argon2.argon2id,
  memoryCost: Number(process.env.ARGON2_MEMORY_KIB ?? 19456),
  timeCost: Number(process.env.ARGON2_TIME_COST ?? 2),
  parallelism: Number(process.env.ARGON2_PARALLELISM ?? 1),
}
const tokenPepper = process.env.TOKEN_PEPPER ?? ''

const BOOTSTRAP_SUPERUSER_EMAIL =
  process.env.BOOTSTRAP_SUPERUSER_EMAIL ?? 'superuser@persistent-memory.local'
const BOOTSTRAP_SUPERUSER_NAME =
  process.env.BOOTSTRAP_SUPERUSER_NAME ?? 'Bootstrap Superuser'
const BOOTSTRAP_WORDS = [
  'Cactus', 'River', 'Signal', 'Copper', 'Atlas', 'Orbit', 'Marble', 'Harbor',
  'Quartz', 'Lumen', 'Falcon', 'Cedar', 'Vector', 'Nimbus', 'Summit', 'Willow',
]

// base64url helper (Node's 'base64url' encoding is URL-safe, no padding).
function b64url(bytes: number): string {
  return randomBytes(bytes).toString('base64url')
}

function pick<T>(arr: readonly T[]): T {
  return arr[randomBytes(1)[0]! % arr.length]!
}

function bootstrapPassword(): string {
  let a = pick(BOOTSTRAP_WORDS)
  let b = pick(BOOTSTRAP_WORDS)
  while (b === a) b = pick(BOOTSTRAP_WORDS)
  const n = 10 + (randomBytes(1)[0]! % 89)
  const s = pick(['!', '#', '%', '*', '+', '-', '?'])
  return `${a}-${b}-${n}${s}`
}

// ── System Settings defaults (Phase 9). The singleton is upserted from the same
// EMBED_* / EMBEDDING_MODE env services/embedding.ts reads, so a fresh install
// starts with an explicit, UI-visible row. Idempotent: re-running preserves an
// admin's saved values via the no-op `update: {}`. The DB enum uses
// `client_bridge` (no hyphen); the wire/env string is `client-bridge`.
const SETTINGS_SINGLETON_ID = 'singleton'
const EMBED_MODEL_DEFAULT = process.env.EMBED_MODEL ?? 'qwen3-embedding:4b'
const EMBED_DIM_DEFAULT = Number(process.env.EMBED_DIM ?? 2560)
const EMBEDDING_MODE_DEFAULT =
  (process.env.EMBEDDING_MODE ?? 'server') === 'client-bridge' ? 'client_bridge' : 'server'
const EXTRACTION_PROVIDER_DEFAULT =
  (process.env.EXTRACTION_PROVIDER ?? 'anthropic') === 'openai' ? 'openai' : 'anthropic'
const EXTRACTION_MODEL_DEFAULT =
  process.env.EXTRACTION_MODEL?.trim() ||
  (EXTRACTION_PROVIDER_DEFAULT === 'openai' ? 'gpt-4o' : 'claude-haiku-4-5-20251001')
const ANTHROPIC_API_KEY_DEFAULT = process.env.ANTHROPIC_API_KEY?.trim() || null
const OPENAI_API_KEY_DEFAULT = process.env.OPENAI_API_KEY?.trim() || null

async function main(): Promise<void> {
  // ── System Settings singleton (upsert from env; never clobber a saved row). ─
  await prisma.systemSettings.upsert({
    where: { id: SETTINGS_SINGLETON_ID },
    update: {}, // preserve any admin-saved values on re-seed
    create: {
      id: SETTINGS_SINGLETON_ID,
      embeddingMode: EMBEDDING_MODE_DEFAULT,
      activeEmbedModel: EMBED_MODEL_DEFAULT,
      activeEmbedDim: EMBED_DIM_DEFAULT,
      factExtractionProvider: EXTRACTION_PROVIDER_DEFAULT,
      factExtractionModel: EXTRACTION_MODEL_DEFAULT,
      factExtractionAnthropicApiKey: ANTHROPIC_API_KEY_DEFAULT,
      factExtractionOpenaiApiKey: OPENAI_API_KEY_DEFAULT,
    },
  })

  // ── LOCAL mode: single-user, no auth → NO demo teams, NO sample mount, NO
  // bootstrap token. The lone local team + super-user are created by the api
  // (ensureLocalIdentity) from the onboarding answers. Demo teams would show up as
  // confusing extra teams (the dashboard would read "Teams: 3"), so skip them here.
  if (process.env.DEPLOYMENT_MODE === 'local') {
    console.log('[seed] DEPLOYMENT_MODE=local — single-user install: skipping demo teams + bootstrap token (the local team + super-user come from the api).')
    return
  }

  // ── Demo teams (upsert by unique name — safe to re-run). ───────────────────
  // Convenience only; the bootstrap super-admin is team-less and creates real
  // teams + members from the dashboard.
  const automationQa = await prisma.team.upsert({
    where: { name: 'Automation QA' },
    update: {},
    create: { name: 'Automation QA' },
  })
  const manualQa = await prisma.team.upsert({
    where: { name: 'Manual QA' },
    update: {},
    create: { name: 'Manual QA' },
  })

  // ── Sample MOUNT: Manual QA mounts Automation QA (grantor=Automation,
  // grantee=Manual) → Manual QA's MCP reads Automation QA's memories (additional).
  // Cross-team is READ-only and gates the MCP only (docs/internal/users_roles.md).
  await prisma.teamGrant.upsert({
    where: {
      grantorTeamId_granteeTeamId: {
        grantorTeamId: automationQa.id,
        granteeTeamId: manualQa.id,
      },
    },
    update: {},
    create: { grantorTeamId: automationQa.id, granteeTeamId: manualQa.id },
  })

  // ── Bootstrap superuser — gated: skip if one already exists. ───────────────
  const existingSuperusers = await prisma.appUser.count({
    where: { adminLevel: 'superuser' },
  })
  if (existingSuperusers > 0) {
    console.log(
      `[seed] Superuser already present (${existingSuperusers}). ` +
        'Skipping bootstrap token mint. Teams/grant ensured.',
    )
    return
  }

  // The bootstrap superuser is INDEPENDENT (team-less) → global cross-team reach
  // on the dashboard. They create real teams + members after first login.
  const tokenId = b64url(8) // public, indexed lookup handle
  const secret = b64url(32) // never persisted in plaintext
  const tokenHash = await argon2.hash(secret + tokenPepper, argonOptions)
  const tempPassword = bootstrapPassword()
  const passwordHash = await argon2.hash(tempPassword + tokenPepper, argonOptions)

  await prisma.appUser.create({
    data: {
      teamId: null, // team-less independent global super-admin
      adminLevel: 'superuser',
      tokenId,
      tokenHash,
      tokenExpires: null, // non-expiring bootstrap token; rotate via the webapp
      tokenIssuedAt: new Date(),
      email: BOOTSTRAP_SUPERUSER_EMAIL,
      displayName: BOOTSTRAP_SUPERUSER_NAME,
      passwordHash,
      passwordTemporary: true,
    },
  })

  const wireToken = `${tokenId}.${secret}`
  const tokenOutputPath = process.env.BOOTSTRAP_TOKEN_OUTPUT_PATH?.trim()
  if (tokenOutputPath) {
    await writeFile(tokenOutputPath, `${wireToken}\n`, { mode: 0o600 })
    await chmod(tokenOutputPath, 0o600)
  }
  // SHOW ONCE — install.sh surfaces this with a copy-now banner. Do NOT log
  // elsewhere; only tokenId + tokenHash live in the DB.
  console.log('\n========================================================')
  console.log(' persistent-memory — BOOTSTRAP SUPERUSER CREDENTIALS (shown ONCE)')
  console.log('========================================================')
  console.log('  Team:  (none — independent global super-admin)')
  console.log(`  Email: ${BOOTSTRAP_SUPERUSER_EMAIL}`)
  console.log(`  Temporary password: ${tempPassword}`)
  console.log(`  Token: ${wireToken}`)
  console.log('--------------------------------------------------------')
  console.log('  Copy these now — they cannot be retrieved later.')
  console.log('  Use the temporary password for first dashboard login,')
  console.log('  then change it immediately. Keep the token as MCP/API')
  console.log('  setup and super-admin recovery access.')
  console.log('  Open the dashboard webapp at http://persistent-memory-management.localhost:3200 and sign')
  console.log('  in with the email + temporary password.')
  console.log('========================================================\n')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (err) => {
    console.error('ERROR: [seed] failed:', err)
    await prisma.$disconnect()
    process.exit(1)
  })
