import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const src = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const root = (path: string) => readFileSync(new URL(`../../../../${path}`, import.meta.url), 'utf8')

function cssRule(selector: string): string {
  const css = src('../app/globals.css')
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = css.match(new RegExp(`${escaped}\\s*{([^}]*)}`))
  return match?.[1] ?? ''
}

describe('table scroll layout contract', () => {
  it('loads the self-hosted material icon package through a reusable icon wrapper', () => {
    const pkg = JSON.parse(root('apps/dashboard/package.json')) as { dependencies: Record<string, string> }
    const layout = src('../app/layout.tsx')
    const icon = src('../components/ui/Icon.tsx')
    const tooltip = src('../components/ui/Tooltip.tsx')
    const statusToggle = src('../components/ui/StatusToggle.tsx')
    const modal = src('../components/ui/Modal.tsx')
    const toast = src('../components/ui/Toast.tsx')

    expect(pkg.dependencies['material-icons']).toBeTruthy()
    expect(layout).toContain("import 'material-icons/iconfont/outlined.css'")
    expect(icon).toContain("import type { MaterialIcon } from 'material-icons'")
    expect(icon).toContain('material-icons-outlined ui-icon')
    expect(tooltip).toContain('createPortal(')
    expect(tooltip).toContain('position.placement')
    expect(tooltip).toContain('VIEWPORT_MARGIN')
    expect(statusToggle).toContain("name={checked ? 'toggle_on' : 'toggle_off'}")
    expect(modal).toContain('<Tooltip label="Close">')
    expect(modal).toContain('name="close"')
    expect(toast).toContain('<Tooltip label="Dismiss">')
    expect(toast).toContain("name=\"close\"")
    expect(toast).not.toContain('title=')
  })

  it('lets shared modal content use available viewport height before scrolling', () => {
    const css = src('../app/globals.css')

    expect(cssRule('.modal')).toContain('max-height: calc(100vh - 48px)')
    expect(cssRule('.modal')).toContain('display: flex')
    expect(cssRule('.modal')).toContain('flex-direction: column')
    expect(css).toContain('.modal-body { padding: 22px; display: flex; flex-direction: column; gap: 16px; min-height: 0; overflow-y: auto; }')
    expect(css).not.toContain('.modal-body { padding: 22px; display: flex; flex-direction: column; gap: 16px; max-height: 60vh')
  })

  it('keeps grid-table headers outside the row scroll area', () => {
    expect(cssRule('.gt.table-scroll')).toMatch(/overflow:\s*hidden/)
    expect(cssRule('.table-scroll')).not.toMatch(/scrollbar-gutter:\s*stable/)
    expect(cssRule('.gt.table-scroll .gt-head')).not.toMatch(/position:\s*sticky/)
    expect(cssRule('.gt-scroll-body')).toMatch(/overflow-y:\s*auto/)
    expect(cssRule('.gt-scroll-body')).toMatch(/overflow-x:\s*hidden/)
    expect(cssRule('.gt-scroll-body')).not.toMatch(/scrollbar-gutter:\s*stable/)
    expect(cssRule('.gt-scroll-body::-webkit-scrollbar')).toMatch(/width:\s*6px/)
  })

  it('keeps Overview cards linked to the exact destination tabs and counts MCP sessions', () => {
    const overview = src('../app/(dashboard)/page.tsx')
    const types = src('../lib/types.ts')
    const css = src('../app/globals.css')
    const overviewApi = root('apps/api/src/routes/dashboard/overview.ts')

    expect(overview).toContain('label="MCP sessions"')
    expect(overview).toContain("href={hrefWithSpace('/services?tab=mcp', space)}")
    expect(overview).toContain("href={hrefWithSpace('/settings?setting=fact-extraction', space)}")
    expect(overview).toContain("href={hrefWithSpace('/settings?setting=embeddings', space)}")
    expect(overview).toContain("const mcpSessions = overview.mcpSessions ?? { active: 0, stream: 0, legacy: 0, serviceStatus: 'unknown' as const }")
    expect(overview).toContain("meta=\"Sessions managed by stream MCP service\"")
    expect(overview).toContain('badge={mcpBadge.label}')
    expect(overview).toContain('badgeTone={mcpBadge.tone}')
    expect(overview).toContain('serviceBadge(overview.services)')
    expect(overview).toContain('workerBadge(overview.workers)')
    expect(overview).toContain('`${overview.services.active} active, ${overview.services.stopped} stopped, ${overview.services.failed} failed`')
    expect(overview).toContain('`${overview.workers.enabled} active, ${workerStoppedCount} stopped, ${overview.workers.failed} failed`')
    expect(overview).toContain('tone="neutral"')
    expect(types).toContain('mcpSessions: {')
    expect(types).toContain('active: number')
    expect(types).toContain('stopped: number')
    expect(types).toContain('failed: number')
    expect(types).toContain('legacy: number')
    expect(types).toContain("serviceStatus: 'running' | 'stopped' | 'error' | 'unknown'")
    expect(overviewApi).toContain('const McpSessionSummary = z.object')
    expect(overviewApi).toContain("serviceStatus: z.enum(['running', 'stopped', 'error', 'unknown'])")
    expect(overviewApi).toContain('mcpServiceStatus(containers)')
    expect(overviewApi).toContain('listMcpClients(settings.mcpSessionIdleTimeoutSeconds)')
    expect(overviewApi).toContain('pruneIdleMcpClients(settings.mcpSessionIdleTimeoutSeconds, now)')
    expect(cssRule('.overview-card.warn')).toContain('border-color: var(--marigold-40)')
    expect(cssRule('.overview-card.bad')).toContain('border-color: var(--coral-40)')
    expect(css).not.toContain('.overview-card.accent { border-color: var(--accent-40)')
    expect(css).not.toContain('.overview-card.ok { border-color: rgba(55, 179, 96')
    expect(css).not.toContain('.overview-card.bad .overview-card-value')
  })

  it.each([
    ['memories', '../app/(dashboard)/memories/MemoriesClient.tsx'],
    ['services', '../app/(dashboard)/services/ServicesClient.tsx'],
    ['workers', '../app/(dashboard)/workers/WorkersClient.tsx'],
    ['team settings', '../app/(dashboard)/team-settings/TeamSettings.tsx'],
    ['usage', '../app/(dashboard)/usage/UsageClient.tsx'],
  ])('%s grid table puts rows in a dedicated scroll body', (_name, file) => {
    const page = src(file)

    expect(page).toContain('className="gt table-scroll"')
    expect(page).toContain('className="gt-head"')
    expect(page).toContain('className="gt-scroll-body"')
  })

  it.each([
    ['users', '../app/(dashboard)/users/page.tsx'],
    ['tokens', '../app/(dashboard)/tokens/page.tsx'],
  ])('%s page uses the fixed-shell internal table scroll pattern', (_name, file) => {
    const page = src(file)

    expect(page).toContain('className="page-fill')
    expect(page).toContain('className="panel table-panel"')
    expect(page).toContain('className="table-scroll native-table-scroll"')
  })

  it('separates stack services from MCP sessions on the Services page', () => {
    const page = src('../app/(dashboard)/services/ServicesClient.tsx')
    const header = src('../components/AppHeader.tsx')

    expect(page).toContain('const mcpServices = services.filter(isMcpService)')
    expect(page).toContain('const stackServices = services.filter')
    expect(page).toContain("const activeTab: 'application' | 'mcp'")
    expect(page).toContain("import { usePathname, useRouter, useSearchParams } from 'next/navigation'")
    expect(page).toContain('const selectServiceTab')
    expect(page).toContain('className="service-view-switcher"')
    expect(page).toContain('className="service-view-separator"')
    expect(page).toContain('role="tablist" aria-label="Services views"')
    expect(page).toContain('Application Services')
    expect(page).toContain('MCP sessions')
    expect(page).not.toContain('services-page-tabs')
    expect(header).not.toContain('selectHeaderTab')
    expect(header).not.toContain('aria-label="Services views"')
    expect(page).not.toContain('className="services-table-toolbar"')
    expect(page).toContain('showLogs({')
    expect(page).toContain('Terminates at')
    expect(page).toContain('formatMcpTerminateCountdown')
    expect(page).toContain('window.setInterval(() => setNowMs(Date.now()), 1_000)')
  })

  it('keeps Services controls in row status toggles and log modals without restart actions', () => {
    const services = src('../app/(dashboard)/services/ServicesClient.tsx')
    const serviceStatus = src('../lib/serviceStatus.ts')
    const css = src('../app/globals.css')

    expect(services).toContain('<div>Status</div>')
    expect(services).toContain('<div>Logs</div>')
    expect(services).toContain("const cols = 'minmax(210px, 1fr) 176px 220px minmax(360px, 2fr)'")
    expect(services).toContain("const toggleAction: 'start' | 'stop' = active ? 'stop' : 'start'")
    expect(services).toContain('const SERVICE_DEPENDENCIES')
    expect(services).toContain("api: ['postgres', 'qdrant', 'redis', 'minio', 'graphiti', 'dlp', 'docker-control']")
    expect(services).toContain('type PendingServiceControl')
    expect(services).toContain("from '@/lib/serviceStatus'")
    expect(serviceStatus).toContain('serviceExitCode')
    expect(serviceStatus).toContain("return code != null && code !== 0 ? 'error' : 'stopped'")
    expect(services).toContain('const dependencyWarnings = dependencyWarningsFor(s)')
    expect(services).toContain('className="service-impact-indicator"')
    expect(services).toContain('name="priority_high"')
    expect(services).toContain('title={`Stop ${pendingControl.service.service}?`}')
    expect(services).toContain('Stop service')
    expect(services).toContain("import { StatusToggle } from '@/components/ui/StatusToggle'")
    expect(services).toContain("import { Tooltip } from '@/components/ui/Tooltip'")
    expect(services).toContain('className="service-status-cell"')
    expect(services).toContain('className="worker-status-progress"')
    expect(services).toContain('className={`worker-status-badge ${statusKind}`}')
    expect(services).toContain('className="status-toggle-dot"')
    expect(services).toContain('<StatusToggle')
    expect(services).toContain('checked={active}')
    expect(services).toContain('onClick={() => requestControl(s, toggleAction)}')
    expect(services).toContain('label="Show credentials"')
    expect(services).toContain('await refresh(true)')
    expect(services).toContain('className="worker-log-cell service-log-cell"')
    expect(services).toContain("import { LogOutput } from '@/components/LogOutput'")
    expect(services).toContain('const [serviceLogPreviews, setServiceLogPreviews] = useState<Record<string, string>>({})')
    expect(services).toContain('const loadServiceLogPreviews = useCallback')
    expect(services).toContain('serviceLogsAction(ref, 40)')
    expect(services).toContain("window.setInterval(() => void loadServiceLogPreviews(refs), 4_000)")
    expect(services).toContain('return [ref, r.error ? `ERROR: ${r.error}` : r.logs] as const')
    expect(services).toContain("import { filterMcpServiceLogs, filterMcpSessionLogs } from '@/lib/logFormat'")
    expect(services).toContain("mode: 'raw' | 'mcp-service' | 'mcp-session'")
    expect(services).toContain('function prepareLogs(raw: string, target: LogTarget): string')
    expect(services).toContain('const servicePreviewLogs = (service: ServiceStatus): string | null =>')
    expect(services).toContain('const mcpSessionPreviewLogs = (client: McpClientStatus, logRef: string | null): string | null =>')
    expect(services).toContain("const mcpCols = 'minmax(260px, 1fr) 132px 170px 154px minmax(340px, 2fr)'")
    expect(services).toContain("const streamMcpService = stackServices.find((s) => s.service === 'mcp' && s.id)")
    expect(services).toContain('const mcpClientLogRef = (client: McpClientStatus): string | null =>')
    expect(services).toContain("'No session communication yet.'")
    expect(services).toContain("'No internal service logs yet.'")
    expect(services).toContain('className={`badge mcp-connection-cell ${client.connectionType ===')
    expect(services).toContain('className="mcp-time-cell"')
    expect(services).toContain('formatServiceDetail(s)')
    expect(services).toContain(".replace(/\\s*\\(not a container\\)\\s*/gi, ' ')")
    expect(services).toContain('<LogOutput')
    expect(services).toContain('text={servicePreviewLogs(s)}')
    expect(services).toContain('showTimeToggle')
    expect(services).toContain('className="worker-log-modal service-log-modal"')
    expect(services).toContain('window.setInterval(() => void loadLogs(logsFor), 4_000)')
    expect(services).not.toContain("onClick={() => void loadLogs(logsFor.ref)}")
    expect(services).not.toContain("logLoading ? 'Reloading")
    expect(services).not.toContain('worker-log-kicker')
    expect(services).not.toContain('Live logs')
    expect(services).not.toContain('formatServiceLogPreview')
    expect(services).not.toContain('formatLogTail')
    expect(services).not.toContain("control(s.service, 'restart')")
    expect(services).not.toContain('>Refresh</button>')
    expect(services).not.toContain('<div style={{ textAlign: \'right\' }}>Actions</div>')
    expect(services).not.toContain('<div style={{ textAlign: \'right\' }}>Control</div>')
    expect(services).not.toContain('mcpClientTerminateAction')
    expect(services).not.toContain('className={`service-status-detail')
    expect(services).not.toContain('{formatStatusDetail(s)}')
    expect(services).not.toContain("!s.controllable ? <div>{s.id ? 'read-only' : 'host-managed'}</div> : null")
    expect(services).not.toContain('className={`worker-toggle service-toggle')
    expect(services).not.toContain('confirm(')
    expect(services).not.toContain('title="Show credentials"')
    expect(services).not.toContain('title={`Copy ${credential.label}`}')

    expect(css).toContain('.service-status-cell')
    expect(css).toContain('.service-title-actions')
    expect(css).toContain('.service-impact-indicator')
    expect(css).toContain('.service-impact-modal')
    expect(cssRule('.service-runtime-detail')).toContain('overflow: hidden')
    expect(cssRule('.service-runtime-detail > div')).toContain('text-overflow: ellipsis')
    expect(css).toContain('.status-toggle-dot')
    expect(cssRule('.status-toggle-dot')).toContain('background: var(--border-strong)')
    expect(css).not.toContain('.service-status-detail')
    expect(css).toContain('.status-toggle-icon')
    expect(cssRule('.status-toggle-icon')).toContain('background: transparent')
    expect(cssRule('.status-toggle-icon.on')).toContain('color: var(--accent)')
    expect(css).not.toContain('.service-toggle:hover')
    expect(css).toContain('.service-log-cell:disabled')
    expect(css).toContain('.mcp-connection-cell')
    expect(cssRule('.mcp-connection-cell')).toContain('width: max-content')
    expect(css).toContain('.mcp-time-cell')
    expect(cssRule('.mcp-time-cell')).toContain('white-space: nowrap')
    expect(css).not.toContain('.worker-log-kicker')
    expect(css).not.toContain('.worker-log-preview')
    expect(cssRule('.log-output-lines')).toContain('white-space: pre-wrap')
    expect(cssRule('.log-output-lines')).toContain('font: 400')
    expect(cssRule('.log-output-preview .log-output-lines')).toContain('-webkit-line-clamp: 4')
    expect(cssRule('.log-level-info')).toContain('color: var(--grass-soft)')
    expect(cssRule('.log-level-warn')).toContain('color: var(--marigold)')
    expect(cssRule('.log-level-error')).toContain('color: var(--coral-soft)')
    expect(cssRule('.log-line-warn .log-message,\n.log-line-warn .log-punctuation')).toContain('color: var(--marigold)')
    expect(cssRule('.log-line-error .log-message,\n.log-line-error .log-punctuation')).toContain('color: var(--coral-soft)')
    expect(cssRule('.worker-log-modal')).toContain('height: calc(100vh - 48px)')
    expect(cssRule('.worker-log-modal')).toContain('display: flex')
    expect(cssRule('.worker-log-modal .modal-body,\n.worker-log-modal-body')).toContain('overflow: hidden')
    expect(cssRule('.worker-log-modal .modal-body,\n.worker-log-modal-body')).toContain('min-height: 0')
    expect(cssRule('.worker-log-modal .log-output-terminal')).toContain('flex: 1 1 auto')
    expect(cssRule('.worker-log-modal .log-output-lines')).toContain('max-height: none')
    expect(cssRule('.services-section-head')).toContain('grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr)')
    expect(cssRule('.service-view-switcher')).toContain('display: inline-flex')
    expect(cssRule('.service-view-switcher')).toContain('justify-self: center')
    expect(cssRule('.service-view-button')).toContain('border-radius: 999px')
    expect(cssRule('.service-view-button')).toContain('min-width: 198px')
    expect(cssRule('.service-view-button.active')).toContain('color: var(--accent)')
    expect(cssRule('.service-view-separator')).toContain('background: var(--border-strong)')
    expect(cssRule('.service-view-separator')).toContain('height: 6px')
  })

  it('keeps terminal log modals pinned to the bottom until the user scrolls up', () => {
    const output = src('../components/LogOutput.tsx')

    expect(output).toContain('const logLinesRef = useRef<HTMLPreElement | null>(null)')
    expect(output).toContain('const autoScrollRef = useRef(true)')
    expect(output).toContain("const shouldAutoScroll = variant === 'terminal'")
    expect(output).toContain('node.scrollTop = node.scrollHeight')
    expect(output).toContain('const distanceFromBottom = node.scrollHeight - node.scrollTop - node.clientHeight')
    expect(output).toContain('autoScrollRef.current = distanceFromBottom <= 24')
    expect(output).toContain('onScroll={handleLogScroll}')
  })

  it('exposes the stream MCP session timeout in System Settings', () => {
    const page = src('../app/(dashboard)/settings/page.tsx')
    const shell = src('../components/settings/SettingsShell.tsx')
    const actions = src('../app/(dashboard)/settings/actions.ts')
    const api = src('../lib/api.ts')
    const types = src('../lib/types.ts')

    expect(page).toContain("import { McpSessionTimeoutForm } from '@/components/McpSessionTimeoutForm'")
    expect(page).toContain('<McpSessionTimeoutForm current={settings} showHeader={false} />')
    expect(page).toContain("id: 'stream-sessions'")
    expect(page).not.toContain('title="System Settings"')
    expect(page).not.toContain('Configure model pins, retention rules')
    expect(page).toContain('<SettingsLayout')
    expect(page).toContain('id="stream-sessions"')
    expect(page).not.toContain("activeSetting === 'stream-sessions'")
    expect(shell).toContain('window.history.pushState')
    expect(shell).toContain('role="tab"')
    expect(shell).not.toContain('<a ')
    expect(shell).not.toContain('<a\n')
    expect(shell).not.toContain('settings-page-head')
    expect(actions).toContain('saveMcpSessionTimeoutAction')
    expect(actions).toContain('mcpSessionIdleTimeoutMinutes')
    expect(api).toContain('putMcpSessionTimeout')
    expect(types).toContain('mcpSessionIdleTimeoutSeconds: number')
  })

  it('auto-refreshes live dashboard monitors without requiring a page reload', () => {
    const services = src('../app/(dashboard)/services/ServicesClient.tsx')
    const usage = src('../app/(dashboard)/usage/UsageClient.tsx')

    expect(services).toContain("import { useCallback, useEffect, useRef, useState } from 'react'")
    expect(services).toContain('const inFlight = useRef(false)')
    expect(services).toContain('window.setInterval(() => void refresh(), 10_000)')

    expect(usage).toContain("import { useCallback, useEffect, useRef, useState } from 'react'")
    expect(usage).toContain('window.setInterval(() => {')
    expect(usage).toContain('void refresh(chartWindow)')
    expect(usage).toContain('if (chartWindow !== TABLE_WINDOW) void refresh(TABLE_WINDOW)')
    expect(usage).not.toContain("if (win !== 'live') return")
  })

  it('uses a full-width token bucket bar chart with explicit time and token axes', () => {
    const usage = src('../app/(dashboard)/usage/UsageClient.tsx')
    const css = src('../app/globals.css')

    expect(usage).toContain('AreaChart')
    expect(usage).toContain('BarChart')
    expect(usage).toContain('ComposedChart')
    expect(usage).toContain('LineChart')
    expect(usage).toContain("import { Select } from '@/components/ui/Select'")
    expect(usage).toContain("type UsageChartStyle =")
    expect(usage).toContain("const [chartStyle, setChartStyle] = useState<UsageChartStyle>('bar')")
    expect(usage).toContain('const CHART_STYLE_OPTIONS')
    expect(usage).toContain("label: 'Bar graph'")
    expect(usage).toContain("label: 'Line · linear'")
    expect(usage).toContain("label: 'Line · monotone'")
    expect(usage).toContain("label: 'Area · linear'")
    expect(usage).toContain("label: 'Area · monotone'")
    expect(usage).toContain("label: 'Composed · bar + line'")
    expect(usage).toContain("label: 'Composed · area + line'")
    expect(usage).not.toContain("label: 'Scatter graph'")
    expect(usage).not.toContain("label: 'Area · basis'")
    expect(usage).not.toContain("label: 'Area · step'")
    expect(usage).not.toContain("label: 'Area · natural'")
    expect(usage).not.toContain("label: 'Line · basis'")
    expect(usage).not.toContain("label: 'Line · natural'")
    expect(usage).not.toContain("label: 'Line · step'")
    expect(usage).not.toContain("label: 'Line · step before'")
    expect(usage).not.toContain("label: 'Line · step after'")
    expect(usage).toContain("const TABLE_WINDOW: UsageWindow = '24h'")
    expect(usage).toContain('const [dataByWindow, setDataByWindow] = useState<Partial<Record<UsageWindow, UsageData>>>')
    expect(usage).toContain('const [chartWindow, setChartWindow] = useState<UsageWindow>(initialWindow)')
    expect(usage).toContain('const [chartNowByWindow, setChartNowByWindow] = useState<Record<UsageWindow, string>>(() => usageClockDefaults())')
    expect(usage).toContain('latestRequestByWindow.current[w] = requestId')
    expect(usage).toContain('setDataByWindow((previous) => ({ ...previous, [w]: next }))')
    expect(usage).toContain('setChartNowByWindow((previous) => ({ ...previous, [w]: fetchedAt.toISOString() }))')
    expect(usage).toContain('const [liveSamples, setLiveSamples] = useState<UsageTrendPoint[]>([])')
    expect(usage).toContain('setLiveSamples((samples) => recordLiveUsageSample(samples, next.totals.tokens, fetchedAt))')
    expect(usage).toContain('const chartData = dataByWindow[chartWindow] ?? emptyUsage(chartWindow)')
    expect(usage).toContain('const tableData = dataByWindow[TABLE_WINDOW] ?? emptyUsage(TABLE_WINDOW)')
    expect(usage).toContain('const chartNow = new Date(chartNowByWindow[chartWindow])')
    expect(usage).toContain('const trend = buildUsageTrend(chartData.trend, chartWindow, chartData.totals.tokens, chartNow, liveSamples)')
    expect(usage).toContain('const xDomain = buildUsageXDomain(chartWindow, trend, chartNow)')
    expect(usage).toContain('const xTicks = buildUsageXAxisTicks(chartWindow, xDomain?.[0], xDomain?.[1])')
    expect(usage).toContain("if (window === '24h') return fmtTrendDateTime(value)")
    expect(usage).toContain('return fmtTrendDate(value)')
    expect(usage).toContain('className="usage-chart"')
    expect(usage).toContain('className="usage-chart-row"')
    expect(usage).toContain('aria-label="Token usage by time bucket"')
    expect(usage).not.toContain('trend.length > 1 ?')
    expect(usage).toContain('<ResponsiveContainer width="100%" height="100%">')
    expect(usage).toContain('<BarChart')
    expect(usage).toContain('<XAxis')
    expect(usage).toContain('dataKey="ts"')
    expect(usage).toContain('type="number"')
    expect(usage).toContain('ticks={xTicks}')
    expect(usage).toContain('tickFormatter={(value) => fmtTrendTick(value, chartWindow)}')
    expect(usage).toContain('<YAxis')
    expect(usage).toContain('<Bar')
    expect(usage).toContain('name="Tokens"')
    expect(usage).toContain("const liveBarSize = chartWindow === 'live' ? 28 : undefined")
    expect(usage).toContain('barSize={liveBarSize}')
    expect(usage).toContain('<Line')
    expect(usage).toContain('<Area')
    expect(usage).not.toContain('<Scatter')
    expect(usage).toContain('Tokens')
    expect(css).toContain('.usage-chart')
    expect(css).toContain('.usage-chart-row')
    expect(css).toContain('.usage-chart-controls')
    expect(css).toContain('.usage-chart-style-select')
    expect(css).toContain('.spark-head')
    expect(css).toContain('.spark-meta')
    expect(css).toContain('grid-template-rows: auto auto')
  })

  it('places Token usage chart controls and polling text in the standard layout', () => {
    const usage = src('../app/(dashboard)/usage/UsageClient.tsx')

    expect(usage).not.toContain('>Refresh</button>')
    expect(usage).not.toContain('void refresh(chartWindow)\n              if (chartWindow !== TABLE_WINDOW)')
    expect(usage).toContain('className="usage-chart-controls"')
    expect(usage).toContain('className="usage-chart-style-select"')
    expect(usage).toContain('<Select')
    expect(usage).toContain('ariaLabel="Token graph style"')
    expect(usage).toContain('className="spark-head"')
    expect(usage).toContain('className="spark-meta">{WINDOW_LABEL[chartWindow]}</div>')
  })

  it('keeps Token usage chart-window controls isolated from lower table tabs', () => {
    const usage = src('../app/(dashboard)/usage/UsageClient.tsx')

    expect(usage).toContain("const [chartWindow, setChartWindow] = useState<UsageWindow>(initialWindow)")
    expect(usage).toContain("const [by, setBy] = useState<UsageView>('service')")
    expect(usage).toContain('onClick={() => setChartWindow(w.v)}')
    expect(usage).toContain("onClick={() => setBy('service')}>By service")
    expect(usage).toContain("onClick={() => setBy('model')}>By model")
    expect(usage).toContain("onClick={() => setBy('user')}>By user requests")
    expect(usage).toContain('<div className="usage-table-panel" hidden={by !== \'service\'}>')
    expect(usage).toContain('<div className="usage-table-panel" hidden={by !== \'model\'}>')
    expect(usage).toContain('<div className="usage-table-panel" hidden={by !== \'user\'}>')
    expect(usage).toContain('<GroupUsageTable groups={serviceGroups} view="service" capabilityHealth={tableData.capabilityHealth} />')
    expect(usage).toContain('<GroupUsageTable groups={modelGroups} view="model" capabilityHealth={tableData.capabilityHealth} />')
    expect(usage).toContain('<UserUsageTable data={tableData} />')
    expect(usage).toContain('Org-wide 24h aggregate')
    expect(usage).not.toContain('buildUsageTrend(chartData.trend, chartWindow, chartData.totals.tokens, new Date()')
  })

  it('has a dedicated Workers page title instead of falling through to Memories', () => {
    const header = src('../components/AppHeader.tsx')

    expect(header).toContain("workers: ['Workers'")
    expect(header).toContain("workers: ['Workers', 'Personal stack scheduled jobs']")
    expect(header).not.toContain('TITLES[seg] ?? TITLES.memories')
  })

  it('keeps Workers controls in schedule and log modals with status start-stop toggles', () => {
    const workers = src('../app/(dashboard)/workers/WorkersClient.tsx')
    const workerSchedule = src('./worker-schedule.ts')
    const css = src('../app/globals.css')

    expect(workers).toContain("import { Modal } from '@/components/ui/Modal'")
    expect(workers).toContain("from '@/lib/worker-schedule'")
    expect(workerSchedule).toContain("export type ScheduleMode = 'never' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'custom'")
    expect(workerSchedule).toContain("hourlyCadence: HourlyCadence")
    expect(workers).toContain("const cols = 'minmax(220px, .9fr) minmax(300px, 1fr) 176px 170px minmax(360px, 2fr)'")
    expect(workers).toContain('className="worker-schedule-cell"')
    expect(workers).toContain('className="worker-schedule-copy"')
    expect(workers).toContain('className="worker-icon-button"')
    expect(workers).toContain('<Icon name="settings"')
    expect(workers).toContain("import { StatusToggle } from '@/components/ui/StatusToggle'")
    expect(workers).toContain("import { Tooltip } from '@/components/ui/Tooltip'")
    expect(workers).toContain('<StatusToggle')
    expect(workers).toContain('checked={w.enabled}')
    expect(workers).toContain('const toggleBusy = busy === `${w.name}:pause` || busy === `${w.name}:resume`')
    expect(workers).toContain("const statusKind = w.status === 'failed' || w.lastError ? 'error' : w.enabled ? 'running' : 'stopped'")
    expect(workers).toContain('className="worker-status-progress"')
    expect(workers).toContain('className={`worker-status-badge ${statusKind}`}')
    expect(workers).toContain('className="status-toggle-dot"')
    expect(workers).toContain('className="worker-run-cell"')
    expect(workers).toContain('label={`Edit schedule for ${w.name}`}')
    expect(workers).toContain('await refresh(true)')
    expect(workers).toContain('<div>Logs</div>')
    expect(workers).toContain('className="worker-log-cell"')
    expect(workers).toContain("import { LogOutput } from '@/components/LogOutput'")
    expect(workers).toContain('function workerLogText(l: WorkerLog): string')
    expect(workers).toContain('`INFO: job ${l.name}`')
    expect(workers).toContain('`INFO: status ${l.status}`')
    expect(workers).toContain('<LogOutput')
    expect(workers).toContain('fallbackTimestamp={w.lastFinishAt ?? w.lastRunAt}')
    expect(workers).toContain('className="worker-schedule-modal"')
    expect(workers).toContain('className="worker-log-modal"')
    expect(workers).toContain('disabled={saveDisabled}')
    expect(workers).toContain('window.setInterval(() => void loadLogs(logsFor), 4_000)')
    expect(workers).toContain('showTimeToggle')
    expect(workers).toContain('className="status-legend"')
    expect(workers).toContain('name="play_circle"')
    expect(workers).toContain('name="pause_circle"')
    expect(workers).toContain('name="error"')
    expect(workers).not.toContain("onClick={() => void loadLogs(logsFor)}")
    expect(workers).not.toContain("logLoading ? 'Reloading")
    expect(workers).not.toContain('worker-log-kicker')
    expect(workers).not.toContain('formatLogTail')
    expect(workers).not.toContain('formatLogText')
    expect(workers).not.toContain('className="worker-log-preview"')
    expect(workers).not.toContain('worker alive')
    expect(workers).not.toContain('worker down')
    expect(workers).not.toContain('heartbeat')
    expect(workers).not.toContain('>{summary}</span>')
    expect(workers).not.toContain('>Refresh')
    expect(workers).not.toContain('<div style={{ textAlign: \'right\' }}>Actions</div>')
    expect(workers).not.toContain('worker-status-detail')
    expect(workers).not.toContain('last {w.status}')
    expect(workers).not.toContain('setEditing')
    expect(workers).not.toContain('function GearIcon')
    expect(workers).not.toContain('className={`worker-toggle')

    expect(css).toContain('.cron-builder')
    expect(cssRule('.worker-schedule-copy')).toContain('min-width: 0')
    expect(cssRule('.worker-schedule-cell')).toContain('overflow: hidden')
    expect(cssRule('.worker-schedule-copy .code-inline')).toContain('text-overflow: ellipsis')
    expect(css).toContain('.worker-status-badge.running')
    expect(css).toContain('.worker-status-badge.healthy')
    expect(css).toContain('.worker-status-badge.stopped')
    expect(css).toContain('.worker-status-badge.error')
    expect(css).toContain('.services-section-capabilities')
    expect(css).toContain('.service-status-description')
    expect(css).toContain('.worker-status-progress')
    expect(css).toContain('.worker-run-cell')
    expect(cssRule('.worker-run-cell')).toContain('white-space: nowrap')
    expect(css).toContain('@keyframes workerStatusProgress')
    expect(css).not.toContain('.worker-status-detail')
    expect(css).toContain('.status-toggle-icon')
    expect(cssRule('.status-toggle-icon')).toContain('background: transparent')
    expect(cssRule('.status-toggle-icon.on')).toContain('color: var(--accent)')
    expect(css).not.toContain('.worker-toggle.on')
    expect(css).toContain('.worker-log-cell')
    expect(css).toContain('.status-legend')
    expect(css).toContain('.legend-icon.running')
    expect(cssRule('.log-output-preview .log-output-lines')).toContain('-webkit-line-clamp: 4')
    expect(cssRule('.log-time-toggle button.active')).toContain('color: var(--accent)')
  })

  it('renders custom selects in a viewport portal so table scroll panels cannot clip options', () => {
    const select = src('../components/ui/Select.tsx')
    const css = src('../app/globals.css')

    expect(select).toContain("import { createPortal } from 'react-dom'")
    expect(select).toContain("import { Icon } from './Icon'")
    expect(select).toContain('name="keyboard_arrow_down"')
    expect(select).toContain('name="check"')
    expect(select).toContain('className="ui-select-list ui-select-portal"')
    expect(cssRule('.ui-select-portal')).toMatch(/position:\s*fixed/)
    expect(css).toContain('z-index: 300')
  })

  it('opens a custom select upward when its options do not fit below the trigger', () => {
    const select = src('../components/ui/Select.tsx')

    expect(select).toContain('const menuHeight = Math.min(260, listRef.current?.scrollHeight ?? 260)')
    expect(select).toContain('const openUpward = spaceBelow < menuHeight && spaceAbove > spaceBelow')
    expect(select).toContain("top: openUpward ? rect.top - maxHeight - 5 : rect.bottom + 5")
  })

  it('keeps custom select hover states neutral instead of inheriting blue button hover', () => {
    const triggerHover = cssRule('.ui-select-trigger:hover')
    const optionActive = cssRule('.ui-select-opt.active')

    expect(triggerHover).toContain('background: var(--inset)')
    expect(triggerHover).toContain('border-color: var(--border-strong)')
    expect(optionActive).toContain('background: var(--elevated)')
    expect(optionActive).not.toContain('var(--accent')
  })

  it('keeps Teams mutations inside the reusable modal flow, not browser confirm prompts', () => {
    const page = src('../app/(dashboard)/teams/page.tsx')
    const client = src('../app/(dashboard)/teams/TeamsClient.tsx')

    expect(page).toContain('<TeamsClient teams={teams} />')
    expect(client).toContain("import { Modal } from '@/components/ui/Modal'")
    expect(client).toContain('Rename team')
    expect(client).toContain('Delete team')
    expect(client).not.toContain('confirm(')
    expect(client).not.toContain('confirm={`')
  })

  it('uses the custom token expiry picker and shows token issue dates', () => {
    const modal = src('../components/TokenModal.tsx')
    const tokens = src('../app/(dashboard)/tokens/page.tsx')

    expect(modal).toContain("import { DateTimePicker } from '@/components/ui/DateTimePicker'")
    expect(modal).not.toContain('type="datetime-local"')
    expect(tokens).toContain('tokenIssuedAt')
    expect(tokens).toContain('issued')
  })

  it('presents mounts as a reader-focused editor using the themed checkbox component', () => {
    const grants = src('../components/GrantMatrix.tsx')

    expect(grants).toContain("import { Checkbox } from '@/components/ui/Checkbox'")
    expect(grants).toContain('Selected reader')
    expect(grants).toContain('Mounted memory sources')
    expect(grants).not.toContain('type="checkbox"')
    expect(grants).not.toContain('owner ↓')
  })

  it('shows client-managed embeddings as an informational pin, not an editable embedding form', () => {
    const page = src('../app/(dashboard)/settings/page.tsx')

    expect(page).toContain("settings.embeddingMode === 'client-bridge'")
    expect(page).toContain('Client-managed embedding pin')
    expect(page).toContain('{settings.embeddingMode ===')
  })

  it('keeps release notes in the header action area, not the sidebar profile footer', () => {
    const nav = src('../components/Nav.tsx')
    const header = src('../components/AppHeader.tsx')

    expect(nav).not.toContain('version-btn')
    expect(nav).not.toContain('/release-history.md')
    expect(header).toContain('/release-history.md')
    expect(header).toContain('APP_VERSION')
    expect(header).toContain("name={localMode ? 'lock' : 'logout'}")
    expect(header).toContain('name="new_releases"')
  })

  it('uses material icons for sidebar links, PM mark, checkbox, and memory row actions', () => {
    const nav = src('../components/Nav.tsx')
    const logo = src('../components/ui/ProductMark.tsx')
    const checkbox = src('../components/ui/Checkbox.tsx')
    const login = src('../app/login/LoginForm.tsx')
    const memories = src('../app/(dashboard)/memories/MemoriesClient.tsx')
    const css = src('../app/globals.css')

    expect(nav).toContain("icon: 'dashboard'")
    expect(nav).toContain("icon: 'memory'")
    expect(nav).toContain("icon: 'dns'")
    expect(nav).toContain("icon: 'work_history'")
    expect(nav).toContain("icon: 'settings'")
    expect(nav).toContain('className="brand-mark"')
    expect(nav).toContain('<ProductMark />')
    expect(login).toContain('<ProductMark />')
    expect(logo).toContain('viewBox="0 0 24 24"')
    expect(logo).toContain('fill="currentColor"')
    expect(nav).toContain('className="nav-icon"')
    expect(checkbox).toContain("checked ? 'check_box' : 'check_box_outline_blank'")
    expect(memories).toContain('className="memory-action-button"')
    expect(memories).toContain('className="memory-category-badges"')
    expect(memories).not.toContain('verifyMemoryAction')
    expect(memories).toContain('name="edit"')
    expect(memories).toContain('name="delete"')
    expect(memories).toContain('label="Open memory details"')
    expect(memories).toContain('label="Delete memory"')
    expect(memories).not.toContain('>Verify</span>')
    expect(memories).not.toContain('>Edit</span>')
    expect(memories).not.toContain('>Delete</span>')
    expect(css).toContain('.brand-mark')
    expect(css).toContain('.brand-mark svg')
    expect(css).toContain('.memory-action-button')
    expect(css).toContain('.ui-tooltip')
    expect(css).toContain('position: fixed')
    expect(css).toContain('z-index: 2147483000')
    expect(css).toContain('--tooltip-bg: rgba(12, 15, 19, .94)')
    expect(css).toContain('backdrop-filter: blur(10px) saturate(1.15)')
    expect(css).toContain('.ui-check > input:checked + .ui-check-box')
  })

  it('keeps the update toast text non-clickable because Details is the action', () => {
    const header = src('../components/AppHeader.tsx')
    const css = src('../app/globals.css')

    expect(header).toContain('<div className="update-toast-main">')
    expect(header).not.toContain('<button type="button" className="update-toast-main"')
    expect(header).toContain('<button type="button" className="secondary" onClick={() => setUpdateOpen(true)}>Details</button>')
    expect(cssRule('.update-toast-main')).not.toMatch(/cursor:\s*pointer/)
    expect(css).not.toContain('.update-toast-main:hover')
  })

  it('reloads stale dashboard tabs and opens release notes after an update lands', () => {
    const header = src('../components/AppHeader.tsx')
    const clientUpdate = root('layers/dashboard/src/lib/clientUpdate.ts')

    expect(header).toContain('postUpdateReloadVersion(APP_VERSION, status)')
    expect(header).toContain('window.localStorage.setItem(POST_UPDATE_RELEASE_NOTES_KEY, reloadVersion)')
    expect(header).toContain('POST_UPDATE_HANDOFF_SEEN_KEY')
    expect(header).toContain('window.localStorage.setItem(POST_UPDATE_HANDOFF_SEEN_KEY, handoff.id)')
    expect(header).toContain('const ready = await waitForUpdateReloadReady(reloadVersion)')
    expect(header).toContain('window.location.reload()')
    expect(header).toContain('const handoffBlocking = isUpdateHandoffBlocking(updateHandoff)')
    expect(header).toContain('const handoffPollingEnabled = shouldPollUpdateHandoff(localMode)')
    expect(header).toContain('if (!handoffPollingEnabled) return undefined')
    expect(header).toContain('const handoffTimer = window.setInterval(() => void refreshUpdateHandoffAndReload(), 1_000)')
    expect(header).toContain('return () => window.clearInterval(handoffTimer)')
    expect(header).toContain('const updatePollMs = handoffBlocking ? 1_000 : updateStatusPollMs(updateStatus)')
    expect(header).toContain("fetch('/api/update/handoff', { cache: 'no-store' })")
    expect(header).toContain('const handoffVersion = handoffReloadVersion(APP_VERSION, handoff, seenHandoffId)')
    expect(header).toContain('window.localStorage.setItem(POST_UPDATE_RELEASE_NOTES_KEY, handoffVersion)')
    expect(header).toContain('if (isUpdateHandoffBlocking(handoff)) {')
    expect(header).toContain('window.location.assign(window.location.href)')
    expect(header).toContain('className="update-handoff-overlay"')
    expect(header).toContain('className="update-handoff-spinner"')
    expect(header).toContain('updateHandoffTitle(updateHandoff)')
    expect(clientUpdate).toContain('Updating Persistent Memory to the latest release')
    expect(header).toContain('role="progressbar"')
    expect(header).toContain("updateHandoff?.phase !== 'failed' ? (")
    expect(header).toContain("minWidth: handoffProgress > 0 ? '4px' : 0")
    expect(cssRule('.update-handoff-title')).toContain('font-size: 18px')
    expect(cssRule('.update-handoff-progress-fill')).not.toContain('var(--success)')
    expect(cssRule('.update-handoff-progress-fill')).not.toContain('background: var(')
    expect(cssRule('.update-handoff-progress-fill')).toContain('background: linear-gradient(90deg, #37B360 0%, #50E68A 100%)')
    expect(cssRule('.update-handoff-progress-fill')).toContain('box-shadow: inset 0 0 0 1px rgba(255, 255, 255, .18)')
    expect(header).toContain('reloadPendingRef.current')
    expect(header).toContain('window.localStorage.getItem(POST_UPDATE_RELEASE_NOTES_KEY)')
    expect(header).toContain('window.localStorage.removeItem(POST_UPDATE_RELEASE_NOTES_KEY)')
    expect(header).toContain('shouldOpenPostUpdateReleaseNotes(APP_VERSION, pendingReleaseNotesVersion)')
    expect(header).toContain('void openReleaseHistory()')
    expect(header).not.toContain('if (!updatesEnabled) return\n    const pendingReleaseNotesVersion')
  })

  it('keeps Memories list/graph/tools tabs in page content before filters with stacked tool cards', () => {
    const memories = src('../app/(dashboard)/memories/MemoriesClient.tsx')
    const header = src('../components/AppHeader.tsx')
    const tools = src('../app/(dashboard)/memories/DashboardTools.tsx')
    const css = src('../app/globals.css')

    expect(memories).toContain('memory-page-tabs')
    expect(memories).toContain("type MemoryView = 'list' | 'graph' | 'tools'")
    expect(memories).toContain("const activeView: MemoryView = requestedView === 'graph'")
    expect(memories).toContain('const fixedMemoryColumn = (width: number) => `minmax(${width}px, ${width}px)`')
    expect(memories).toContain("const contentTrack = 'minmax(0, 1fr)'")
    expect(memories).toContain('fixedMemoryColumn(projectWidth)')
    expect(memories).toContain('fixedMemoryColumn(categoryWidth)')
    expect(memories).toContain('fixedMemoryColumn(authorWidth)')
    expect(memories).toContain('fixedMemoryColumn(actionsWidth)')
    expect(memories).not.toContain('max-content')
    expect(memories.indexOf('memory-page-tabs')).toBeLessThan(memories.indexOf('memory-filter-row'))
    expect(memories).toContain('aria-label="Memory sections"')
    expect(memories).toContain('Memory List ({total.toLocaleString()})')
    expect(memories).toContain('Memory Graph')
    expect(memories).toContain('<MemoryGraphShell surface={surface} />')
    expect(memories).toContain('Memory Tools')
    expect(memories).toContain('selectMemoryTab')
    expect(memories).toContain("router.replace(queryString ? `${pathname}?${queryString}` : pathname, { scroll: false })")
    expect(header).not.toContain('aria-label="Memory sections"')
    expect(header).not.toContain('Memory List')
    expect(header).not.toContain('Memory Tools')
    expect(css).toContain('.memory-page-tabs')
    expect(cssRule('.memory-filter-row > .ui-input-wrap')).toContain('flex: 1 1 auto')
    expect(css).toContain('.confidence-range-panel')
    expect(memories).not.toContain('Total memories')
    expect(tools).toContain('className="memory-tools-stack"')
    expect(tools).toContain('Export memory')
    expect(tools).toContain('Import memory')
    expect(tools).toContain('Bulk delete')
    expect(tools).toContain('Load & verify')
    expect(tools).toContain('Import & re-embed')
    expect(tools).toContain('Error details')
    expect(css).toContain('.import-steps')
    expect(css).toContain('.import-error-list')
  })

  it('keeps graph focus, rail sizing, and inspector scrolling in the app-owned layout', () => {
    const graph = src('../app/(dashboard)/memories/graph/MemoryGraphShell.tsx')
    const graphCss = src('../app/globals.css')

    expect(graph).toContain("FILTER_RAIL_STORAGE_KEY = 'pm:memory-graph:filter-rail-width:v1'")
    expect(graph).toContain('window.localStorage.getItem(FILTER_RAIL_STORAGE_KEY)')
    expect(graph).toContain('window.localStorage.setItem(FILTER_RAIL_STORAGE_KEY, String(clamped))')
    expect(graph).toContain('aria-label="Resize graph filters"')
    expect(graph).toContain('buildFocusedGraph(nodes, edges, selectedId)')
    expect(graph).toContain('setAutoOverview(false)')
    expect(graph).toContain('LIVE_ACTIVITY_TTL_MS')
    expect(graph).toContain('GRAPH_PULSE_DURATION_MS')
    expect(graph).toContain('const nodesRef = useRef<MemoryGraphNode[]>([])')
    expect(graph).toContain('setPulseIds([...touched])')
    expect(graph).not.toContain('queueMicrotask(() => setPulseIds')
    expect(graph).toContain('Activity colors: read cyan, created green, updated amber')
    expect(graph).toContain('<strong>Live activity</strong>')
    expect(graph).toContain('<strong>Details</strong>')
    expect(graph).toContain('className="memory-graph-accessible-list-body"')
    expect(cssRule('.memory-graph-filter-rail')).toContain('overflow-x: hidden')
    expect(graphCss).toContain('.memory-graph-inspector { border-left: 1px solid var(--divider-section); display: grid; grid-template-rows: minmax(0, 1fr) minmax(0, 1fr); overflow: hidden; }')
    expect(cssRule('.memory-graph-accessible-list-body')).toContain('flex: 1 1 0')
    expect(cssRule('.memory-graph-accessible-list-body')).not.toContain('max-height')
    expect(graphCss).toContain('@keyframes memoryGraphTargetWave')
  })

  it('keeps bulk deletion team-free in Personal and fixed to the current team in Shared', () => {
    const memories = src('../app/(dashboard)/memories/MemoriesClient.tsx')
    const tools = src('../app/(dashboard)/memories/DashboardTools.tsx')

    expect(memories).toContain('const canUseMemoryTools = isPersonalSurface || !!who.teamId')
    expect(tools).toContain("const isPersonalSurface = surface === 'personal'")
    expect(tools).toContain('const canReview = isPersonalSurface || Boolean(effectiveTeam)')
    expect(tools).toContain('const teamProjects = isPersonalSurface')
    expect(tools).toContain('disabled={!canReview}')
    expect(tools).toContain("{!isPersonalSurface ? <div><span>Team</span>")
    expect(tools).toContain('onRequestBulkDelete')
    expect(tools).not.toContain('Team to bulk-delete')
    expect(tools).not.toContain('confirm(`Delete ALL memories')
  })

  it('renders the graph-primary warning badge without a decorative icon', () => {
    const memories = src('../app/(dashboard)/memories/MemoriesClient.tsx')

    expect(memories).toContain('graph primary')
    expect(memories).not.toContain('<Icon name="account_tree" size={13} />')
  })

  it('loads memories incrementally and resets cursor pagination when badge or score filters change', () => {
    const memories = src('../app/(dashboard)/memories/MemoriesClient.tsx')
    const actions = src('../app/(dashboard)/memories/actions.ts')

    expect(memories).toContain('const [nextCursor, setNextCursor]')
    expect(memories).toContain('new IntersectionObserver')
    expect(memories).toContain('ariaLabel="Filter by badge"')
    expect(memories).toContain('<ConfidenceRangeSelect')
    expect(memories).toContain("min={scoreMin || '0.0'}")
    expect(memories).toContain("max={scoreMax || '1.0'}")
    expect(actions).toContain('cursor?: string')
    expect(actions).toContain('scoreMin?: number')
    expect(actions).toContain('scoreMax?: number')
  })
})
