/** @pm/shared/embeddings — public surface of the embedding adapter. */
export type { Embedder, EmbedResult } from './embedder.ts'
export type { EmbedConfig } from './config.ts'
export type { ModelSpec } from './registry.ts'
export { resolveEmbedConfig } from './config.ts'
export { MODEL_REGISTRY, validateModelDim } from './registry.ts'
export { makeEmbedder, makeEmbedderFromEnv, makeEmbedderForPin } from './factory.ts'
export { OllamaEmbedder } from './ollama.ts'
export { VoyageEmbedder } from './voyage.ts'
export { OpenAIEmbedder } from './openai.ts'
export { vectorName } from './naming.ts'
export { chunkBatches, withRetry, fetchJson, assertDim } from './batch.ts'
export { setEmbedUsageSink, emitEmbedUsage, estimateTokens } from './usage-sink.ts'
export type { EmbedUsageEvent } from './usage-sink.ts'
